### ISSUE TITLE
"Login expired - go to freedom.konscript.com/renew" event

### ISSUE THREAD

**Issue by honzajavorek** [sqren/freedom#1]
Hello, your app is super-awesome and very useful. Thank you for creating and maintaining it!

I have one little bug report. Lately the calendar started to contain following event, usually placed on the next day or so:

![login](https://f.cloud.github.com/assets/283441/1022303/bec45bf6-0d79-11e3-9c5d-e2b4bf17e0f4.png)

There is nothing really working or helping on http://freedom.konscript.com/renew, though.

I tried to go through the registration process again from the project's homepage, but it freezes during the first point (Get Facebook Events), after clicking the button I see "AJAX spinner circle" only, no action.

Otherwise the app works great, all future events are loaded and I can properly see them in my calendar. I just wandered what that special event means and if I am doing something wrong or what I am supposed to do with it.

**Comment by gidders28** [comment]
I'm having the same issues : I got the login expired message & followed the instructions - nothing

So I re registered but when I tried adding it to my google calender I get a message 

Settings error - could not fetch URL

:(
